import re, json, requests
import urllib.request
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from .. import models, schemas
from ..database import get_db

router = APIRouter()


# ── Helpers ───────────────────────────────────────────────────────────────────

def extract_video_id(url: str) -> str | None:
    url = url.strip()
    patterns = [
        r'[?&]v=([a-zA-Z0-9_-]{11})',
        r'youtu\.be/([a-zA-Z0-9_-]{11})',
        r'youtube\.com/embed/([a-zA-Z0-9_-]{11})',
        r'youtube\.com/shorts/([a-zA-Z0-9_-]{11})',
        r'youtube\.com/live/([a-zA-Z0-9_-]{11})',
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    if re.match(r'^[a-zA-Z0-9_-]{11}$', url):
        return url
    return None


def get_video_title(video_id: str) -> str:
    try:
        oembed = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={video_id}&format=json"
        with urllib.request.urlopen(oembed, timeout=5) as r:
            return json.loads(r.read().decode())['title']
    except Exception:
        return f"YouTube: {video_id}"


def fetch_transcript(video_id: str, lang: str) -> tuple[list[dict], bool]:
    """
    Fetch captions via youtube-transcript-api.
    Works for videos with publicly accessible transcripts (TED-Ed, etc.).
    Returns (entries, is_autogenerated).
    """
    from youtube_transcript_api import YouTubeTranscriptApi

    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

    manual = None
    for t in transcript_list:
        if not t.is_generated:
            manual = t
            break

    is_autogenerated = manual is None

    if manual is not None:
        try:
            raw = transcript_list.find_manually_created_transcript([lang]).fetch()
        except Exception:
            raw = manual.fetch()
    else:
        try:
            raw = transcript_list.find_generated_transcript([lang]).fetch()
        except Exception:
            raw = next(iter(transcript_list)).fetch()

    entries = [{'text': e['text'], 'start': e['start'], 'duration': e.get('duration', 2.0)} for e in raw]
    return entries, is_autogenerated


def _parse_caption_format(ext: str, raw: str) -> list[dict]:
    if ext == 'json3':
        data = json.loads(raw)
        result = []
        for ev in data.get('events', []):
            if not ev.get('segs'):
                continue
            text = ' '.join(s.get('utf8', '') for s in ev['segs']).replace('\n', ' ').strip()
            if text:
                result.append({
                    'text':     text,
                    'start':    ev['tStartMs'] / 1000,
                    'duration': ev.get('dDurationMs', 2000) / 1000,
                })
        return result

    if ext == 'srv3':
        import xml.etree.ElementTree as ET
        root = ET.fromstring(raw)
        result = []
        for p in root.iter('p'):
            text = ''.join(s.text or '' for s in p.iter('s')).replace('\n', ' ').strip()
            if text:
                result.append({
                    'text':     text,
                    'start':    int(p.get('t', 0)) / 1000,
                    'duration': int(p.get('d', 2000)) / 1000,
                })
        return result

    # VTT / TTML fallback
    result = []
    for block in raw.split('\n\n'):
        if '-->' not in block:
            continue
        lines = [l.strip() for l in block.split('\n') if l.strip()]
        time_line = next((l for l in lines if '-->' in l), None)
        if not time_line:
            continue
        def to_s(t):
            t = t.split('.')[0]
            parts = t.split(':')
            return sum(int(p) * (60 ** (len(parts) - 1 - i)) for i, p in enumerate(parts))
        start_s = time_line.split('-->')[0].strip()
        end_s   = time_line.split('-->')[1].strip().split()[0]
        text    = ' '.join(l for l in lines if '-->' not in l and not l.isdigit()).strip()
        if text:
            s = to_s(start_s)
            result.append({'text': text, 'start': s, 'duration': to_s(end_s) - s})
    return result


def build_segments(entries: list[dict], words_per_seg: int = 15) -> list[dict]:
    segments, cur = [], {"start_ms": 0, "end_ms": 0, "words": []}
    for entry in entries:
        text  = entry['text'].replace('\n', ' ').strip()
        start = int(entry['start'] * 1000)
        end   = int((entry['start'] + entry.get('duration', 2.0)) * 1000)
        if not text:
            continue
        if not cur['words']:
            cur['start_ms'] = start
        cur['end_ms'] = end
        cur['words'].extend(text.split())
        if len(cur['words']) >= words_per_seg:
            segments.append({
                'start': cur['start_ms'] // 1000,
                'end':   cur['end_ms']   // 1000,
                'text':  ' '.join(cur['words']),
            })
            cur = {"start_ms": 0, "end_ms": 0, "words": []}
    if cur['words']:
        segments.append({
            'start': cur['start_ms'] // 1000,
            'end':   cur['end_ms']   // 1000,
            'text':  ' '.join(cur['words']),
        })
    return segments


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/listen-stories", response_model=list[schemas.VideoStoryResponse])
def get_listen_stories(lang: str, db: Session = Depends(get_db)):
    return (
        db.query(models.VideoStory)
        .filter(models.VideoStory.lang == lang)
        .order_by(models.VideoStory.sequence_order)
        .all()
    )


@router.post("/listen-stories/from-url", response_model=schemas.VideoStoryResponse)
def create_from_url(payload: schemas.ListenFromUrl, db: Session = Depends(get_db)):
    video_id = extract_video_id(payload.url)
    if not video_id:
        raise HTTPException(400, "Could not find a YouTube video ID in that URL.")

    existing = (
        db.query(models.VideoStory)
        .filter(models.VideoStory.video_id == video_id, models.VideoStory.lang == payload.lang)
        .first()
    )
    if existing:
        return existing

    try:
        entries, is_autogenerated = fetch_transcript(video_id, payload.lang)
    except Exception as exc:
        msg = str(exc).lower()
        if 'disabled' in msg or 'no transcript' in msg or 'could not retrieve' in msg:
            raise HTTPException(404, "This video has no captions.")
        raise HTTPException(422, "Could not fetch transcript — the video may be restricted or captions are not publicly accessible.")

    segments = build_segments(entries)
    if not segments:
        raise HTTPException(422, "Transcript is empty.")

    story = models.VideoStory(
        video_id         = video_id,
        source_type      = 'youtube',
        title            = get_video_title(video_id),
        lang             = payload.lang,
        source           = 'YouTube',
        segments         = segments,
        is_autogenerated = is_autogenerated,
    )
    db.add(story)
    db.commit()
    db.refresh(story)
    return story
