from fastapi import APIRouter, HTTPException
from youtube_transcript_api import (
    YouTubeTranscriptApi,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
)

router = APIRouter()

@router.get("/transcript")
def get_transcript(v: str):
    """
    Fetch manually created captions for a YouTube video.
    Rejects auto-generated (ASR) transcripts — they have too many errors
    for dictation practice.
    Returns events in json3-compatible format.
    """
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(v)
    except TranscriptsDisabled:
        raise HTTPException(status_code=404, detail="Captions are disabled for this video.")
    except VideoUnavailable:
        raise HTTPException(status_code=404, detail="Video unavailable or private.")
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))

    # Try English manual transcript first, then any manual language.
    transcript_obj = None
    try:
        transcript_obj = transcript_list.find_manually_created_transcript(['en', 'en-US', 'en-GB'])
    except NoTranscriptFound:
        # No English manual — try any manually created language
        manual = [t for t in transcript_list if not t.is_generated]
        if not manual:
            raise HTTPException(
                status_code=422,
                detail="This video only has auto-generated captions, which have too many errors for dictation practice. Choose a video with manually reviewed subtitles."
            )
        transcript_obj = manual[0]

    try:
        entries = transcript_obj.fetch()
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Could not fetch transcript: {e}")

    events = [
        {
            "tStartMs":    int(entry["start"] * 1000),
            "dDurationMs": int(entry["duration"] * 1000),
            "segs":        [{"utf8": entry["text"]}],
        }
        for entry in entries
        if entry.get("text", "").strip()
    ]

    return {
        "events": events,
        "_track": {
            "lang": transcript_obj.language_code,
            "name": transcript_obj.language,
        },
    }


@router.get("/transcript-segments")
def get_transcript_segments(v: str, lang: str = "en"):
    """
    Return timed segments for a YouTube video WITHOUT writing to the database.
    The frontend caches the result in IndexedDB keyed by video_id+lang.
    Accepts both manual and auto-generated captions (caller decides what to do with is_autogenerated).
    """
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(v)
    except TranscriptsDisabled:
        raise HTTPException(404, "Captions are disabled for this video.")
    except VideoUnavailable:
        raise HTTPException(404, "Video is unavailable or private.")
    except Exception as e:
        msg = str(e)
        if "429" in msg or "Too Many Requests" in msg:
            raise HTTPException(429, "YouTube is rate-limiting this server right now. Try again in a few minutes.")
        raise HTTPException(404, msg)

    # Prefer manually created transcript in requested language, then fall back gracefully.
    is_auto = False
    transcript_obj = None
    try:
        transcript_obj = transcript_list.find_manually_created_transcript([lang, "en"])
    except NoTranscriptFound:
        manual_any = [t for t in transcript_list if not t.is_generated]
        if manual_any:
            transcript_obj = manual_any[0]
        else:
            # Accept auto-generated as a fallback
            try:
                transcript_obj = transcript_list.find_generated_transcript([lang, "en"])
            except NoTranscriptFound:
                transcript_obj = next(iter(transcript_list), None)
            is_auto = True

    if transcript_obj is None:
        raise HTTPException(404, "No captions found for this video.")

    try:
        raw = transcript_obj.fetch()
    except Exception as e:
        raise HTTPException(502, f"Could not fetch caption data: {e}")

    # Build ~15-word segments with millisecond timestamps.
    segments, cur = [], {"start_ms": 0, "end_ms": 0, "words": []}
    for entry in raw:
        text = entry.get("text", "").replace("\n", " ").strip()
        if not text:
            continue
        start_ms = int(entry["start"] * 1000)
        end_ms   = int((entry["start"] + entry.get("duration", 2.0)) * 1000)
        if not cur["words"]:
            cur["start_ms"] = start_ms
        cur["end_ms"] = end_ms
        cur["words"].extend(text.split())
        if len(cur["words"]) >= 15:
            segments.append({
                "start": cur["start_ms"] // 1000,
                "end":   cur["end_ms"]   // 1000,
                "text":  " ".join(cur["words"]),
            })
            cur = {"start_ms": 0, "end_ms": 0, "words": []}
    if cur["words"]:
        segments.append({
            "start": cur["start_ms"] // 1000,
            "end":   cur["end_ms"]   // 1000,
            "text":  " ".join(cur["words"]),
        })

    if not segments:
        raise HTTPException(422, "This video's transcript appears to be empty.")

    # Fetch video title via YouTube oEmbed (no API key required).
    import urllib.request as _ur, json as _json
    title = f"YouTube: {v}"
    try:
        oembed_url = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={v}&format=json"
        with _ur.urlopen(oembed_url, timeout=5) as r:
            title = _json.loads(r.read().decode()).get("title", title)
    except Exception:
        pass

    return {
        "video_id":         v,
        "title":            title,
        "lang":             transcript_obj.language_code,
        "is_autogenerated": is_auto,
        "segments":         segments,
    }
