import json
import os
import tempfile
import urllib.request

import yt_dlp
from fastapi import APIRouter, HTTPException
from youtube_transcript_api import (
    YouTubeTranscriptApi,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
)

from app.config import settings

router = APIRouter()

# /transcript: curated listen stories, manual captions only

@router.get("/transcript")
def get_transcript(v: str):
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(v)
    except TranscriptsDisabled:
        raise HTTPException(status_code=404, detail="Captions are disabled for this video.")
    except VideoUnavailable:
        raise HTTPException(status_code=404, detail="Video unavailable or private.")
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))

    transcript_obj = None
    try:
        transcript_obj = transcript_list.find_manually_created_transcript(["en", "en-US", "en-GB"])
    except NoTranscriptFound:
        manual = [t for t in transcript_list if not t.is_generated]
        if not manual:
            raise HTTPException(
                status_code=422,
                detail="This video only has auto-generated captions, which have too many errors for dictation practice. Choose a video with manually reviewed subtitles."
            )
        transcript_obj = manual[0]

    try:
        entries = transcript_obj.fetch()
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Could not fetch transcript: {e}")

    events = [
        {
            "tStartMs":    int(entry["start"] * 1000),
            "dDurationMs": int(entry["duration"] * 1000),
            "segs":        [{"utf8": entry["text"]}],
        }
        for entry in entries
        if entry.get("text", "").strip()
    ]

    return {
        "events": events,
        "_track": {
            "lang": transcript_obj.language_code,
            "name": transcript_obj.language,
        },
    }


# /transcript-segments: user YouTube imports, no DB write.
# Uses yt-dlp for caption extraction (avoids youtube-transcript-api 429s).
# Falls back to Groq Whisper when no captions exist.

_WHISPER_LANG = {"arz": "ar"}  # map non-ISO-639-1 codes Whisper does not accept


def _video_title(video_id):
    try:
        url = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={video_id}&format=json"
        with urllib.request.urlopen(url, timeout=5) as r:
            return json.loads(r.read().decode()).get("title", f"YouTube: {video_id}")
    except Exception:
        return f"YouTube: {video_id}"


def _parse_json3(data):
    entries = []
    for ev in data.get("events", []):
        segs = ev.get("segs")
        if not segs:
            continue
        text = " ".join(s.get("utf8", "") for s in segs).replace("\n", " ").strip()
        if text:
            entries.append({
                "text":     text,
                "start":    ev["tStartMs"] / 1000,
                "duration": ev.get("dDurationMs", 2000) / 1000,
            })
    return entries


def _build_segments(entries, words=15):
    segments = []
    cur = {"s": 0, "e": 0, "w": []}
    for entry in entries:
        text = (entry.get("text") or "").strip()
        if not text:
            continue
        s_ms = int(entry["start"] * 1000)
        e_ms = int((entry["start"] + entry.get("duration", 2.0)) * 1000)
        if not cur["w"]:
            cur["s"] = s_ms
        cur["e"] = e_ms
        cur["w"].extend(text.split())
        if len(cur["w"]) >= words:
            segments.append({"start": cur["s"] // 1000, "end": cur["e"] // 1000, "text": " ".join(cur["w"])})
            cur = {"s": 0, "e": 0, "w": []}
    if cur["w"]:
        segments.append({"start": cur["s"] // 1000, "end": cur["e"] // 1000, "text": " ".join(cur["w"])})
    return segments


def _fetch_url(url):
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None


def _get_captions_ytdlp(video_id, lang):
    """Use yt-dlp to get subtitle data without downloading audio.
    Returns (entries, is_autogenerated, actual_lang). entries=[] when no captions found."""
    ydl_opts = {"skip_download": True, "quiet": True, "no_warnings": True, "socket_timeout": 20}
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
    except Exception as e:
        raise RuntimeError(f"yt-dlp info extraction failed: {e}")

    manual = info.get("subtitles", {})
    auto   = info.get("automatic_captions", {})

    def best_sub_url(track):
        for try_lang in [lang, "en"] + list(track.keys()):
            if try_lang not in track:
                continue
            for fmt in track[try_lang]:
                if fmt.get("ext") == "json3":
                    return try_lang, fmt["url"]
            if track[try_lang]:
                return try_lang, track[try_lang][0].get("url")
        return None, None

    picked_lang, sub_url = best_sub_url(manual)
    is_auto = False
    if not sub_url:
        picked_lang, sub_url = best_sub_url(auto)
        is_auto = bool(sub_url)

    if not sub_url:
        return [], False, lang

    data = _fetch_url(sub_url)
    if not data:
        return [], False, lang

    return _parse_json3(data), is_auto, picked_lang or lang


def _groq_transcribe(audio_path, lang):
    import groq as groq_sdk
    whisper_lang = _WHISPER_LANG.get(lang, lang if len(lang) == 2 else None)
    client = groq_sdk.Groq(api_key=settings.GROQ_API_KEY)
    with open(audio_path, "rb") as f:
        resp = client.audio.transcriptions.create(
            file=(os.path.basename(audio_path), f),
            model="whisper-large-v3",
            response_format="verbose_json",
            timestamp_granularities=["segment"],
            language=whisper_lang,
        )
    return [
        {"text": seg.text.strip(), "start": float(seg.start), "duration": float(seg.end) - float(seg.start)}
        for seg in (resp.segments or [])
        if seg.text.strip()
    ]


def _download_and_transcribe(video_id, lang):
    if not settings.GROQ_API_KEY:
        raise HTTPException(503, "This video has no captions. Set GROQ_API_KEY to enable audio transcription.")
    with tempfile.TemporaryDirectory() as tmpdir:
        ydl_opts = {
            "format":         "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio",
            "outtmpl":        os.path.join(tmpdir, "audio.%(ext)s"),
            "quiet":          True,
            "no_warnings":    True,
            "socket_timeout": 30,
        }
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([f"https://www.youtube.com/watch?v={video_id}"])
        except Exception as e:
            raise HTTPException(502, f"Audio download failed: {e}")

        audio_files = [f for f in os.listdir(tmpdir) if f.startswith("audio.")]
        if not audio_files:
            raise HTTPException(502, "Audio download produced no output file.")
        try:
            return _groq_transcribe(os.path.join(tmpdir, audio_files[0]), lang)
        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(502, f"Whisper transcription failed: {e}")


@router.get("/transcript-segments")
def get_transcript_segments(v: str, lang: str = "en"):
    """Return timed segments without DB write; frontend caches in IndexedDB.
    1. yt-dlp -> subtitle URLs (avoids 429s from youtube-transcript-api)
    2. No captions -> yt-dlp audio + Groq Whisper large-v3
    """
    try:
        entries, is_auto, actual_lang = _get_captions_ytdlp(v, lang)
    except RuntimeError as e:
        raise HTTPException(502, str(e))

    if not entries:
        entries = _download_and_transcribe(v, lang)
        is_auto = True
        actual_lang = lang

    segments = _build_segments(entries)
    if not segments:
        raise HTTPException(422, "This video transcript appears to be empty.")

    return {
        "video_id":         v,
        "title":            _video_title(v),
        "lang":             actual_lang,
        "is_autogenerated": is_auto,
        "segments":         segments,
    }
