from .database import Base
from sqlalchemy import ARRAY, TIMESTAMP, BigInteger, Column, Integer, String, Boolean, Uuid, JSON, UniqueConstraint
from sqlalchemy.sql.expression import text
from sqlalchemy.orm import relationship
from sqlalchemy.sql.schema import ForeignKey


class User(Base):
    __tablename__ = "users"
    id           = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    username     = Column(String, nullable=False, unique=True, index=True)
    email        = Column(String, nullable=False, unique=True, index=True)
    password     = Column(String, nullable=False)
    created_at   = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text('now()'))
    proficiency  = Column(String)   # CEFR level: A1 A2 B1 B2 C1 C2
    native_lang  = Column(String)   # e.g. 'en', 'es'

class UserWord(Base):
    __tablename__ = "user_words"

    id         = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    user_id    = Column(Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    word       = Column(String, nullable=False)
    lang       = Column(String, nullable=False)
    seen_count = Column(Integer, server_default=text("1"))
    first_seen = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    last_seen  = Column(TIMESTAMP(timezone=True), server_default=text("now()"))
    stories    = Column(ARRAY(String))

class UserProgress(Base):
    __tablename__ = "user_progress"

    id             = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    user_id        = Column(Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    story_id       = Column(String, nullable=False)   # UUID or 'l<timestamp>' for local stories
    story_title    = Column(String)
    lang           = Column(String, nullable=False)
    tab            = Column(String, nullable=False)   # 'retype' | 'speak'
    sentence_index = Column(Integer, nullable=False, server_default=text("0"))
    updated_at     = Column(TIMESTAMP(timezone=True), server_default=text("now()"))

class UserVocab(Base):
    __tablename__ = "user_vocab"

    id         = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    user_id    = Column(Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    word       = Column(String, nullable=False)
    lang       = Column(String, nullable=False)
    pos        = Column(String)
    definition = Column(String)
    example    = Column(String)
    saved_at   = Column(TIMESTAMP(timezone=True), server_default=text("now()"))

class CuratedStory(Base):
    __tablename__ = "curated_stories"

    id             = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    title          = Column(String, nullable=False)
    content        = Column(String, nullable=False)
    franco         = Column(String)
    lang           = Column(String, nullable=False)
    author         = Column(String)
    source         = Column(String)
    sequence_order = Column(Integer)
    created_at     = Column(TIMESTAMP(timezone=True), server_default=text('now()'))

class WordCache(Base):
    __tablename__ = "word_cache"

    id         = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    word       = Column(String, nullable=False, index=True)
    lang       = Column(String, nullable=False, index=True)
    pos        = Column(String)
    definition = Column(String)
    example    = Column(String)
    source     = Column(String, server_default='wiktionary')
    created_at = Column(TIMESTAMP(timezone=True), server_default=text('now()'))

class VideoStory(Base):
    __tablename__ = "video_stories"

    id             = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    video_id       = Column(String, nullable=True, index=True)    # YouTube video ID; null for non-YouTube sources
    audio_url      = Column(String)                                # direct audio stream URL (TED, podcast, etc.)
    source_type    = Column(String, nullable=False, server_default=text("'youtube'"))  # 'youtube'|'ted'|'podcast'|'upload'
    title          = Column(String, nullable=False)
    lang           = Column(String, nullable=False, index=True)
    author         = Column(String)                                # channel / speaker
    source         = Column(String)                                # e.g. 'TED', 'DW', 'BBC'
    segments         = Column(JSON, nullable=False)                  # [{start, end, text}, ...]
    is_autogenerated = Column(Boolean, server_default=text('false')) # true when captions are ASR-generated
    sequence_order   = Column(Integer)
    created_at       = Column(TIMESTAMP(timezone=True), server_default=text('now()'))


class CommunityStory(Base):
    __tablename__ = "community_stories"

    id         = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    title      = Column(String, nullable=False)
    content    = Column(String, nullable=False)
    franco     = Column(String)
    lang       = Column(String, nullable=False)
    author     = Column(String)
    source     = Column(String)
    reviewed   = Column(Boolean, server_default=text('false'))
    created_at = Column(TIMESTAMP(timezone=True), server_default=text('now()'))


class UserStory(Base):
    __tablename__ = "user_stories"

    id         = Column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    user_id    = Column(Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title      = Column(String, nullable=False)
    content    = Column(String, nullable=False)
    franco     = Column(String)
    lang       = Column(String, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), server_default=text('now()'))


class FrequencySource(Base):
    __tablename__ = "frequency_sources"

    id   = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False, unique=True)
    url  = Column(String)


class FrequencyLemma(Base):
    __tablename__ = "frequency_lemmas"

    id               = Column(BigInteger, primary_key=True, autoincrement=True)
    language_code    = Column(String(10), nullable=False, index=True)
    normalized_lemma = Column(String, nullable=False)

    __table_args__ = (UniqueConstraint("language_code", "normalized_lemma"),)


class FrequencyEntry(Base):
    __tablename__ = "frequency_entries"

    id        = Column(BigInteger, primary_key=True, autoincrement=True)
    lemma_id  = Column(BigInteger, ForeignKey("frequency_lemmas.id"), nullable=False, index=True)
    source_id = Column(Integer, ForeignKey("frequency_sources.id"), nullable=False)
    rank      = Column(Integer, index=True)
    raw_count = Column(BigInteger)

    __table_args__ = (UniqueConstraint("lemma_id", "source_id"),)


class CorpusSentence(Base):
    __tablename__ = "corpus_sentences"

    id            = Column(BigInteger, primary_key=True, autoincrement=True)
    language_code = Column(String(10), nullable=False, index=True)
    sentence      = Column(String, nullable=False)
    source        = Column(String(50), nullable=False, server_default="leipzig")
    score         = Column(Integer, nullable=False, index=True)  # 0–100, higher = better example
