<!-- ListenView.vue — two modes: dictation practice and phrase-in-context scenes. -->
<template>
  <!-- Hidden YouTube IFrame container — must be a real DOM node (dictation player) -->
  <div ref="ytContainerEl" style="width:0;height:0;overflow:hidden;position:absolute;pointer-events:none;" />

  <!-- HTML5 audio element for non-YouTube dictation sources -->
  <audio
    v-if="selectedStory && selectedStory.source_type !== 'youtube'"
    ref="audioEl"
    :src="selectedStory.audio_url"
    preload="metadata"
    @loadedmetadata="onAudioLoaded"
    @timeupdate="onAudioTimeUpdate"
    @play="isPlaying = true; startWave()"
    @pause="isPlaying = false; stopWave()"
    @ended="isPlaying = false; stopWave()"
    style="display:none"
  />

  <!-- ── Mode tabs ── -->
  <div class="flex gap-1 bg-gray-900 rounded-full p-0.5 self-start">
    <button
      @click="mode = 'dictation'"
      :class="['text-xs px-4 py-1.5 rounded-full transition-all font-medium',
        mode === 'dictation' ? 'bg-gray-700 text-white' : 'text-gray-500 hover:text-gray-300']"
    >🎧 {{ t(lang, 'listeningExercises') }}</button>
    <button
      @click="mode = 'scenes'"
      :class="['text-xs px-4 py-1.5 rounded-full transition-all font-medium',
        mode === 'scenes' ? 'bg-emerald-700 text-white' : 'text-gray-500 hover:text-gray-300']"
    >🎬 Phrase Scenes</button>
  </div>

  <!-- ══════════════════════════════════════════════════════════════════════════
       DICTATION MODE
  ═══════════════════════════════════════════════════════════════════════════ -->
  <div v-show="mode === 'dictation'" class="flex flex-col gap-3">

    <!-- Story picker -->
    <div v-if="!selectedStory" class="flex flex-col gap-3">

      <div v-if="storiesLoading" class="text-sm text-gray-500 text-center py-10">{{ t(lang, 'loading') }}</div>
      <div v-else-if="storiesError" class="text-sm text-red-400 text-center py-6">{{ storiesError }}</div>
      <div v-else-if="!stories.length" class="text-sm text-gray-500 text-center py-10">
        {{ t(lang, 'noExercises') }}
      </div>
      <div v-else class="flex flex-col gap-2">
        <button
          v-for="story in stories"
          :key="story.id"
          @click="loadStory(story)"
          class="w-full text-left bg-slate-900 border border-gray-700 hover:border-emerald-700 rounded-lg px-4 py-3 transition-all"
        >
          <div class="font-medium text-sm text-gray-100 leading-snug">{{ story.title }}</div>
          <div class="text-xs text-gray-500 mt-0.5 flex gap-2 flex-wrap">
            <span v-if="story.author">{{ story.author }}</span>
            <span v-if="story.source" class="text-gray-600">{{ story.source }}</span>
            <span>{{ story.segments.length }} {{ t(lang, 'segment') }}</span>
            <span v-if="story.is_autogenerated" class="text-yellow-600">{{ t(lang, 'autoCaptions') }}</span>
          </div>
        </button>
      </div>
    </div>

    <!-- Player -->
    <div v-else class="flex flex-col gap-4">

      <!-- Back + header -->
      <div class="flex items-start gap-3">
        <button
          @click="backToList"
          class="flex-shrink-0 text-gray-500 hover:text-white text-lg leading-none pt-0.5 transition-all"
          title="Back to list"
        >←</button>
        <div class="flex flex-col gap-0.5 min-w-0 flex-1">
          <h2 class="font-semibold text-gray-100 text-base leading-snug">{{ selectedStory.title }}</h2>
          <div class="text-xs text-gray-500 flex gap-2">
            <span v-if="selectedStory.author">{{ selectedStory.author }}</span>
            <span v-if="selectedStory.source" class="uppercase tracking-wide">{{ selectedStory.source }}</span>
            <span>{{ LANGS[selectedStory.lang]?.name ?? selectedStory.lang }}</span>
          </div>
        </div>
        <button
          v-if="resumeSegment !== null"
          @click="resumeFromSaved"
          class="flex-shrink-0 text-xs text-emerald-400 border border-emerald-800 rounded-md px-2.5 py-1 hover:bg-emerald-950 transition-all"
        >{{ t(lang, 'resumeSeg') }} {{ resumeSegment + 1 }}</button>
      </div>

      <!-- Auto-generated transcript warning -->
      <div
        v-if="selectedStory.is_autogenerated"
        class="text-xs text-yellow-400 bg-yellow-950 border border-yellow-800 rounded-lg px-3 py-2"
      >
        {{ t(lang, 'autoGeneratedWarning') }}
      </div>

      <!-- Difficulty toggle -->
      <div class="flex gap-1.5">
        <button
          v-for="d in ['easy', 'medium', 'hard']"
          :key="d"
          @click="difficulty = d"
          :class="['text-xs px-3 py-1.5 rounded-full transition-all',
            difficulty === d ? 'bg-emerald-700 text-white' : 'bg-gray-800 text-gray-400 hover:text-white']"
        >{{ t(lang, d) }}</button>
      </div>

      <!-- Waveform + timing -->
      <div class="bg-slate-900 rounded-xl px-4 pt-4 pb-3 flex flex-col gap-2">
        <svg width="100%" height="60" viewBox="0 0 400 60" preserveAspectRatio="none">
          <rect
            v-for="(h, i) in bars"
            :key="i"
            :x="i * 10 + 1"
            :width="8"
            :y="(60 - h) / 2"
            :height="h"
            rx="2"
            :fill="isPlaying ? '#10b981' : '#065f46'"
            :opacity="isPlaying ? 0.85 : 0.4"
          />
        </svg>
        <div class="flex justify-between text-xs text-gray-500">
          <span>{{ t(lang, 'segment') }} {{ segmentIdx + 1 }} / {{ segments.length }}</span>
          <span>{{ fmtTime(currentTime) }} / {{ fmtTime(segDuration) }}</span>
        </div>
      </div>

      <!-- Player error -->
      <div v-if="playerError" class="text-xs text-red-400 text-center py-2">{{ playerError }}</div>

      <!-- Controls -->
      <div class="flex items-center justify-center gap-6">
        <button
          @click="rewind"
          :disabled="!playerReady"
          class="text-sm text-gray-400 hover:text-white disabled:opacity-30 transition-all flex flex-col items-center gap-0.5"
        >
          <span class="text-lg">⏮</span>
          <span class="text-xs">10s</span>
        </button>

        <button
          @click="togglePlay"
          :disabled="!playerReady"
          :class="['w-14 h-14 rounded-full text-2xl flex items-center justify-center transition-all',
            playerReady ? 'bg-emerald-700 hover:bg-emerald-600 text-white' : 'bg-gray-800 text-gray-600']"
        >{{ isPlaying ? '⏸' : '▶' }}</button>

        <button
          @click="seekToSegmentStart"
          :disabled="!playerReady"
          class="text-sm text-gray-400 hover:text-white disabled:opacity-30 transition-all flex flex-col items-center gap-0.5"
        >
          <span class="text-lg">↩</span>
          <span class="text-xs">restart</span>
        </button>
      </div>

      <div v-if="!playerReady && !playerError" class="text-xs text-gray-500 text-center">
        {{ t(lang, 'loadingPlayer') }}
      </div>

      <!-- Input area -->
      <div class="flex flex-col gap-2">
        <textarea
          v-model="userInput"
          rows="3"
          :placeholder="t(lang, 'typeWhatYouHear')"
          class="w-full bg-slate-900 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-100 outline-none focus:border-emerald-600 resize-none placeholder:text-gray-600 transition-all"
        />

        <!-- Word-by-word colour feedback -->
        <div v-if="comparedWords.length" class="flex flex-wrap gap-1.5 px-1">
          <span
            v-for="(w, i) in comparedWords"
            :key="i"
            :class="['text-sm px-1.5 py-0.5 rounded font-mono transition-colors',
              w.state === 'correct' ? 'bg-emerald-900 text-emerald-300' :
              w.state === 'wrong'   ? 'bg-purple-900 text-purple-300' :
                                      'text-gray-500']"
          >{{ w.typed }}</span>
        </div>

        <!-- Accuracy badge -->
        <div v-if="accuracy !== null" class="flex justify-end">
          <span class="text-xs text-gray-500">
            {{ t(lang, 'accuracy') }}: <span class="text-emerald-400 font-medium">{{ accuracy }}%</span>
            <span class="ml-1 text-gray-600">({{ correctCount }}/{{ segmentWords.length }} {{ t(lang, 'words') }})</span>
          </span>
        </div>
      </div>

      <!-- Transcript reveal -->
      <div
        v-if="showTranscript && currentSegment"
        class="bg-slate-900 border border-emerald-800 rounded-lg px-4 py-3 text-sm text-gray-200 leading-relaxed"
      >{{ currentSegment.text }}</div>

      <!-- Action row -->
      <div class="flex items-center justify-between gap-2">
        <div class="flex items-center gap-2">
          <button
            @click="showTranscript = !showTranscript"
            class="text-xs px-3 py-1.5 rounded-md border border-gray-700 text-gray-400 hover:border-emerald-700 hover:text-emerald-400 transition-all"
          >{{ showTranscript ? t(lang, 'hideTranscript') : t(lang, 'showCorrectText') }}</button>

          <button
            v-if="selectedStory.audio_url"
            @click="downloadAudio"
            :disabled="downloadingAudio"
            class="text-xs px-3 py-1.5 rounded-md border border-gray-700 text-gray-400 hover:border-sky-700 hover:text-sky-400 disabled:opacity-40 transition-all"
            title="Download audio for offline use"
          >{{ downloadingAudio ? '…' : t(lang, 'downloadAudio') }}</button>
        </div>

        <button
          @click="nextSegment"
          :disabled="segmentIdx >= segments.length - 1"
          class="text-xs px-4 py-1.5 rounded-md bg-emerald-700 text-white hover:bg-emerald-600 disabled:opacity-40 transition-all"
        >{{ t(lang, 'nextSegment') }}</button>
      </div>

    </div>
  </div>

  <!-- ══════════════════════════════════════════════════════════════════════════
       PHRASE SCENES MODE  (YouGlish widget)
       Type any word or expression and see native speakers using it in the wild.
  ═══════════════════════════════════════════════════════════════════════════ -->
  <div v-show="mode === 'scenes'" class="flex flex-col gap-4">

    <!-- Explainer -->
    <p class="text-xs text-gray-500 leading-relaxed">
      Type a word or expression — see how native speakers use it in real video clips.
    </p>

    <!-- Search row -->
    <div class="flex gap-2">
      <input
        v-model="phraseQuery"
        :dir="isRTL(lang) ? 'rtl' : 'ltr'"
        placeholder="e.g.  مساءك فل · bonjour · wie geht's"
        @keydown.enter="searchScenes"
        class="flex-1 bg-slate-900 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-100 outline-none focus:border-emerald-600 placeholder:text-gray-600 transition-all"
      />
      <button
        @click="searchScenes"
        :disabled="!phraseQuery.trim()"
        class="px-5 py-2 bg-emerald-700 text-white text-sm font-medium rounded-lg hover:bg-emerald-600 disabled:opacity-40 transition-all whitespace-nowrap"
      >Find scenes</button>
    </div>

    <!-- Language badge -->
    <div v-if="ygLanguage" class="flex items-center gap-1.5 text-xs text-gray-500">
      <span class="w-1.5 h-1.5 rounded-full bg-emerald-600 inline-block" />
      Searching in {{ ygLanguage }}
    </div>

    <!-- Widget wrapper — always in DOM so the widget instance survives tab switches. -->
    <!-- YouGlish injects its iframe into #szol-yg-widget. -->
    <div
      v-show="activePhrase"
      class="rounded-xl overflow-hidden border border-gray-800 bg-black"
      style="min-height: 360px;"
    >
      <div id="szol-yg-widget" ref="ygContainerEl" />
    </div>

    <!-- No results -->
    <p v-if="ygNoResults" class="text-xs text-gray-500 text-center py-4">
      No clips found for "<span class="text-gray-300">{{ activePhrase }}</span>" in {{ LANGS[lang]?.name }}.
      Try a shorter phrase or check the spelling.
    </p>

    <!-- Idle state — nothing searched yet -->
    <div v-if="!activePhrase && !ygNoResults" class="flex flex-col items-center gap-3 py-8 text-center">
      <div class="text-3xl opacity-30">🎬</div>
      <p class="text-xs text-gray-600 max-w-xs">
        Search for any expression above and watch short clips of real speakers using it in context.
      </p>
    </div>

  </div>

</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import Fuse from 'fuse.js'
import { LANGS } from '../data/stories.js'
import { fetchListenStories } from '../utils/api.js'
import { t } from '../utils/i18n.js'
import { isRTL } from '../utils/rtl.js'

const props = defineProps({
  story:       Object,
  lang:        String,
  currentUser: Object,
})

// ── Mode ──────────────────────────────────────────────────────────────────────

const mode = ref('dictation')

watch(mode, newMode => {
  if (newMode === 'scenes') {
    // Pause any active dictation player when switching tabs.
    if (player?.pauseVideo) player.pauseVideo()
    if (audioEl.value) audioEl.value.pause()
  }
})

// ── Story list ────────────────────────────────────────────────────────────────

const stories        = ref([])
const storiesLoading = ref(false)
const storiesError   = ref('')
const selectedStory  = ref(null)

async function loadStories() {
  storiesLoading.value = true
  storiesError.value   = ''
  try {
    stories.value = await fetchListenStories(props.lang)
  } catch {
    storiesError.value = 'Could not load listening exercises.'
  } finally {
    storiesLoading.value = false
  }
}

watch(() => props.lang, () => {
  backToList()
  loadStories()
  // Reset scenes state when language changes.
  phraseQuery.value  = ''
  activePhrase.value = ''
  ygNoResults.value  = false
})

// ── Load a story into the player ──────────────────────────────────────────────

const segments       = ref([])
const segmentIdx     = ref(0)
const userInput      = ref('')
const showTranscript = ref(false)
const resumeSegment  = ref(null)
const difficulty     = ref('medium')

async function loadStory(story) {
  teardown()
  selectedStory.value  = story
  segments.value       = story.segments
  segmentIdx.value     = 0
  userInput.value      = ''
  showTranscript.value = false

  const saved = JSON.parse(localStorage.getItem('szol_listen_progress') || '{}')
  const vp    = saved[story.id]
  resumeSegment.value = (vp && vp.segmentIndex > 0 && vp.segmentIndex < story.segments.length)
    ? vp.segmentIndex : null

  if (story.source_type === 'youtube') {
    loadYTApi(story.video_id)
  } else {
    await nextTick()
    if (audioEl.value) {
      audioEl.value.currentTime = story.segments[0]?.start ?? 0
      if (audioEl.value.readyState >= 1) onAudioLoaded()
    }
  }
}

function backToList() {
  teardown()
  selectedStory.value  = null
  segments.value       = []
  segmentIdx.value     = 0
  userInput.value      = ''
  showTranscript.value = false
  resumeSegment.value  = null
}

// ── YouTube player (dictation) ────────────────────────────────────────────────

const ytContainerEl = ref(null)
const playerReady   = ref(false)
const playerError   = ref('')
const isPlaying     = ref(false)
const currentTime   = ref(0)
const duration      = ref(0)

let player    = null
let pollTimer = null

function initPlayer(id) {
  if (!ytContainerEl.value) return
  try {
    player = new window.YT.Player(ytContainerEl.value, {
      width:    0,
      height:   0,
      videoId:  id,
      playerVars: { controls: 0, rel: 0, disablekb: 1, fs: 0, modestbranding: 1, iv_load_policy: 3 },
      events: {
        onReady(e) {
          playerReady.value = true
          duration.value    = e.target.getDuration() || 0
          e.target.seekTo(segments.value[segmentIdx.value]?.start ?? 0, true)
          e.target.pauseVideo()
        },
        onStateChange(e) {
          const playing = e.data === window.YT.PlayerState.PLAYING
          isPlaying.value = playing
          if (playing) {
            startWave()
            pollTimer = setInterval(pollYTTime, 400)
          } else {
            stopWave()
            clearInterval(pollTimer)
            pollTimer = null
          }
        },
        onError() {
          playerError.value = 'Video unavailable — it may be restricted or deleted.'
          playerReady.value = false
        },
      },
    })
  } catch {
    playerError.value = 'Could not load the YouTube player.'
  }
}

function loadYTApi(id) {
  if (window.YT?.Player) { initPlayer(id); return }
  window.onYouTubeIframeAPIReady = () => initPlayer(id)
  if (!document.querySelector('script[src*="youtube.com/iframe_api"]')) {
    const s   = document.createElement('script')
    s.src     = 'https://www.youtube.com/iframe_api'
    s.onerror = () => { playerError.value = 'Failed to load YouTube API.' }
    document.head.appendChild(s)
  }
}

function pollYTTime() {
  if (!player?.getCurrentTime) return
  currentTime.value = player.getCurrentTime()
  const seg = segments.value[segmentIdx.value]
  if (seg && currentTime.value >= seg.end) {
    player.pauseVideo()
    currentTime.value = seg.end
  }
}

// ── HTML5 audio handlers ──────────────────────────────────────────────────────

const audioEl = ref(null)

function onAudioLoaded() {
  playerReady.value = true
  duration.value    = audioEl.value?.duration || 0
  const startAt = segments.value[segmentIdx.value]?.start ?? 0
  if (audioEl.value && Math.abs(audioEl.value.currentTime - startAt) > 1) {
    audioEl.value.currentTime = startAt
  }
}

function onAudioTimeUpdate() {
  if (!audioEl.value) return
  currentTime.value = audioEl.value.currentTime
  const seg = segments.value[segmentIdx.value]
  if (seg && currentTime.value >= seg.end) {
    audioEl.value.pause()
    currentTime.value = seg.end
  }
}

// ── Unified player controls ───────────────────────────────────────────────────

function isYouTubeStory() { return selectedStory.value?.source_type === 'youtube' }

function togglePlay() {
  if (!playerReady.value) return
  if (isYouTubeStory()) {
    isPlaying.value ? player.pauseVideo() : player.playVideo()
  } else {
    isPlaying.value ? audioEl.value.pause() : audioEl.value.play()
  }
}

function rewind() {
  if (!playerReady.value) return
  const segStart = segments.value[segmentIdx.value]?.start ?? 0
  const newTime  = Math.max(segStart, (isYouTubeStory() ? player.getCurrentTime() : audioEl.value.currentTime) - 10)
  seekTo(newTime)
}

function seekToSegmentStart() {
  if (!playerReady.value) return
  seekTo(segments.value[segmentIdx.value]?.start ?? 0)
}

function seekTo(t) {
  if (isYouTubeStory()) {
    player.seekTo(t, true)
  } else if (audioEl.value) {
    audioEl.value.currentTime = t
  }
  currentTime.value = t
}

function nextSegment() {
  if (segmentIdx.value >= segments.value.length - 1) return
  const next = segments.value[segmentIdx.value + 1]
  seekTo(next.start)
  if (isYouTubeStory()) player.pauseVideo()
  else if (audioEl.value) audioEl.value.pause()
  segmentIdx.value++
  userInput.value      = ''
  showTranscript.value = false
}

// ── Teardown ──────────────────────────────────────────────────────────────────

function teardown() {
  clearInterval(pollTimer); pollTimer = null
  stopWave()
  if (player?.destroy) { player.destroy(); player = null }
  if (audioEl.value)   { audioEl.value.pause(); audioEl.value.currentTime = 0 }
  playerReady.value = false
  playerError.value = ''
  isPlaying.value   = false
  currentTime.value = 0
  duration.value    = 0
}

// ── Segment state ─────────────────────────────────────────────────────────────

const currentSegment = computed(() => segments.value[segmentIdx.value] ?? null)

const segDuration = computed(() => {
  const seg = currentSegment.value
  return seg ? (seg.end - seg.start) : 0
})

function fmtTime(secs) {
  const s = Math.floor(secs || 0)
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

// ── Waveform ──────────────────────────────────────────────────────────────────

const BASE_HEIGHTS = Array.from({ length: 40 }, (_, i) => {
  const envelope = Math.sin((i / 39) * Math.PI)
  const detail   = Math.sin(i * 1.7) * 0.25
  return Math.max(4, Math.round((envelope * 0.6 + detail + 0.5) * 44 + 6))
})

const bars = ref([...BASE_HEIGHTS])
let waveTimer = null

function startWave() {
  if (waveTimer) return
  waveTimer = setInterval(() => {
    bars.value = BASE_HEIGHTS.map(base => Math.max(4, Math.min(56, base + (Math.random() - 0.5) * 28)))
  }, 90)
}

function stopWave() {
  clearInterval(waveTimer); waveTimer = null
  bars.value = [...BASE_HEIGHTS]
}

// ── Word comparison ───────────────────────────────────────────────────────────

function normalizeWord(w) {
  return w.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]/g, '')
}

function wordMatch(typed, expected) {
  if (difficulty.value === 'hard')  return typed === expected
  const t = normalizeWord(typed)
  const e = normalizeWord(expected)
  if (difficulty.value === 'medium') return t === e
  return new Fuse([e], { threshold: 0.4 }).search(t).length > 0
}

const segmentWords = computed(() => (currentSegment.value?.text ?? '').split(/\s+/).filter(Boolean))
const userWords    = computed(() => userInput.value.trim().split(/\s+/).filter(w => w))

const comparedWords = computed(() =>
  userWords.value.map((w, i) => {
    const expected = segmentWords.value[i]
    if (!expected) return { typed: w, state: 'extra' }
    return { typed: w, state: wordMatch(w, expected) ? 'correct' : 'wrong' }
  })
)

const correctCount = computed(() => comparedWords.value.filter(w => w.state === 'correct').length)

const accuracy = computed(() => {
  if (!userWords.value.length) return null
  return Math.round((correctCount.value / segmentWords.value.length) * 100)
})

// ── localStorage progress ─────────────────────────────────────────────────────

function saveProgress() {
  if (!selectedStory.value) return
  const all = JSON.parse(localStorage.getItem('szol_listen_progress') || '{}')
  all[selectedStory.value.id] = { segmentIndex: segmentIdx.value, timestamp: Date.now() }
  localStorage.setItem('szol_listen_progress', JSON.stringify(all))
}

function resumeFromSaved() {
  const idx = resumeSegment.value
  resumeSegment.value  = null
  segmentIdx.value     = idx
  userInput.value      = ''
  showTranscript.value = false
  seekTo(segments.value[idx]?.start ?? 0)
}

watch(segmentIdx, saveProgress)

// ── Audio download ────────────────────────────────────────────────────────────

const downloadingAudio = ref(false)

async function downloadAudio() {
  if (!selectedStory.value?.audio_url) return
  downloadingAudio.value = true
  try {
    const res  = await fetch(selectedStory.value.audio_url)
    const blob = await res.blob()
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    const ext  = selectedStory.value.audio_url.split('.').pop().split('?')[0] || 'mp3'
    a.download = `${selectedStory.value.title}.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  } finally {
    downloadingAudio.value = false
  }
}

// ── Phrase Scenes (YouGlish widget) ──────────────────────────────────────────

const phraseQuery   = ref('')
const activePhrase  = ref('')
const ygNoResults   = ref(false)
const ygContainerEl = ref(null)

// Maps app language codes to YouGlish language names.
const YOUGLISH_LANG = {
  en: 'english',  es: 'spanish',  fr: 'french',   de: 'german',
  it: 'italian',  ru: 'russian',  he: 'hebrew',   ar: 'arabic',
  arz: 'arabic',  ja: 'japanese', zh: 'chinese',  hu: 'hungarian',
  el: 'greek',
}

// Human-readable language name for the badge shown under the search bar.
const ygLanguage = computed(() => {
  const name = YOUGLISH_LANG[props.lang]
  return name ? name.charAt(0).toUpperCase() + name.slice(1) : null
})

let ygWidget = null

function loadYGScript(cb) {
  if (window.YG?.Widget) { cb(); return }
  // Script already injected — poll until the global is ready.
  if (document.querySelector('script[src*="youglish.com/public/emb/widget.js"]')) {
    const poll = setInterval(() => {
      if (window.YG?.Widget) { clearInterval(poll); cb() }
    }, 150)
    return
  }
  const s   = document.createElement('script')
  s.src     = 'https://youglish.com/public/emb/widget.js'
  s.charset = 'utf-8'
  // Give the script a tick to register YG on the window after load.
  s.onload  = () => setTimeout(cb, 250)
  document.head.appendChild(s)
}

function searchScenes() {
  const q = phraseQuery.value.trim()
  if (!q) return
  activePhrase.value = q
  ygNoResults.value  = false

  loadYGScript(() => {
    if (!window.YG?.Widget) return

    const ygLang = YOUGLISH_LANG[props.lang] ?? 'english'

    if (!ygWidget) {
      // Create the widget once — it injects its iframe into #szol-yg-widget.
      ygWidget = new window.YG.Widget('szol-yg-widget', {
        width:      640,
        components: 9,    // video + captions + navigation
        events: {
          onFetchDone(data) { ygNoResults.value = data.totalResult === 0 },
          onError()         { ygNoResults.value = true },
        },
      })
    }

    ygWidget.pronounce(q, ygLang)
  })
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

onMounted(() => {
  loadStories()
  // Pre-load YouTube iframe API (used by dictation player).
  if (!document.querySelector('script[src*="youtube.com/iframe_api"]')) {
    const s = document.createElement('script')
    s.src   = 'https://www.youtube.com/iframe_api'
    document.head.appendChild(s)
  }
})

onUnmounted(() => {
  teardown()
  ygWidget = null
})
</script>
