<!-- NavBar.vue: the navigation bar at the top of every page. -->
<!-- It shows the app name, tab buttons, language selector, and the ⚙ settings icon. -->
<template>
  <!-- <nav> is a semantic HTML element meaning "navigation". -->
  <!-- "flex items-center justify-between" = flexbox row, items vertically centered, spaced to edges. -->
  <!-- "px-6 py-3" = horizontal padding 1.5rem, vertical padding 0.75rem. -->
  <!-- "border-b border-gray-200" = thin gray line at the bottom of the nav. -->
  <nav class="flex items-center justify-between px-6 py-3 border-b border-gray-200">

    <!-- Brand / logo area: shows the app name "Szól". -->
    <!-- "text-xl font-semibold tracking-tight" = large text, semi-bold, slightly tighter letter spacing. -->
    <div class="text-xl font-semibold tracking-tight">
      <!-- The ó is wrapped in a span so it can be colored differently (emerald green). -->
      Sz<span class="text-emerald-500">ó</span>l
    </div>

    <!-- Tab buttons: one button per tab, generated by looping through the "tabs" array. -->
    <div class="flex gap-1">
      <!-- v-for loops over the tabs array and renders one button for each tab. -->
      <!-- "tab in tabs" means: for each item (named "tab") in the "tabs" array. -->
      <!-- :key="tab.key" gives each button a unique ID so Vue can track them efficiently. -->
      <button
        v-for="tab in tabs"
        :key="tab.key"
        @click="$emit('tab', tab.key)"
        :class="[
          'px-4 py-1.5 rounded-md text-sm transition-all',
          active === tab.key
            ? 'bg-gray-100 text-gray-900 font-medium'
            : 'text-gray-500 hover:text-gray-900'
        ]"
      >
        <!-- Display the translated label for this tab. -->
        {{ tab.label }}
      </button>
    </div>

    <!-- Right side: language dropdown + settings gear button. -->
    <div class="flex items-center gap-2">
      <!-- Language selector dropdown. -->
      <!-- :value="lang" sets which option is currently selected (bound to the lang prop). -->
      <!-- @change fires when the user picks a different language. -->
      <!-- $emit('lang', ...) sends the 'lang' event up to App.vue with the new language code. -->
      <!-- $event.target.value is the value of the selected <option> element. -->
      <select
        :value="lang"
        @change="$emit('lang', $event.target.value)"
        class="text-sm border border-gray-200 rounded-md px-2 py-1 bg-white"
      >
        <!-- v-for loops over the LANGS object. Each iteration gives: l = language config, code = 'es'/'el'/etc. -->
        <!-- :value="code" is what gets submitted when this option is selected. -->
        <option v-for="(l, code) in LANGS" :key="code" :value="code">
          {{ l.name }}
        </option>
      </select>

      <!-- Settings gear button. Clicking it emits the 'tab' event with 'settings'. -->
      <!-- :class applies different styles depending on whether Settings is the active tab. -->
      <!-- title="Settings" shows a tooltip on hover. -->
      <button
        @click="$emit('tab', 'settings')"
        :class="[
          'text-lg px-1.5 py-0.5 rounded-md transition-all',
          active === 'settings' ? 'text-gray-900' : 'text-gray-400 hover:text-gray-700'
        ]"
        title="Settings"
      >⚙</button>

      <!-- User icon: opens AuthModal when logged out, shows username + logout when logged in. -->
      <div v-if="!currentUser">
        <button
          @click="$emit('auth')"
          class="text-lg px-1.5 py-0.5 rounded-md text-gray-400 hover:text-gray-700 transition-all"
          title="Login / Register"
        >👤</button>
      </div>
      <div v-else class="flex items-center gap-1.5">
        <span class="text-xs text-gray-600 max-w-20 truncate">{{ currentUser.username }}</span>
        <button
          @click="$emit('logout')"
          class="text-xs text-gray-300 hover:text-red-400 transition-all"
          title="Logout"
        >✕</button>
      </div>
    </div>

  </nav>
</template>

<script setup>
// computed creates a derived value that auto-updates when its dependencies change.
import { computed } from 'vue'

// Import the LANGS object (language configurations) and the t() translation function.
import { LANGS } from '../data/stories.js'
import { t }     from '../utils/i18n.js'

// defineProps() declares what data this component expects to receive from its parent (App.vue).
// active: which tab is currently selected (e.g. 'read', 'library').
// lang: the current language code (e.g. 'es', 'el').
const props = defineProps({
  active:      String,
  lang:        String,
  currentUser: Object, // null when logged out, user object when logged in
})

defineEmits(['tab', 'lang', 'auth', 'logout'])

// tabs is a computed array of tab objects. It recalculates whenever props.lang changes
// so tab labels update when the language switches (e.g. "Read" → "Leer" in Spanish).
// t(props.lang, 'read') looks up the translation of 'read' for the current language.
// Read tab is intentionally omitted — reading happens through active retyping.
// Loading a story from Library navigates directly to Retype.
const tabs = computed(() => [
  { key: 'retype',  label: t(props.lang, 'retype') },
  { key: 'speak',   label: t(props.lang, 'speak') },
  { key: 'write',   label: t(props.lang, 'write') },
  { key: 'chat',    label: '💬 Tutor' },
  { key: 'vocab',   label: t(props.lang, 'vocab') },
  { key: 'library', label: t(props.lang, 'library') },
])
</script>
