/**
 * Semitic root annotation — Hebrew and Arabic.
 *
 * Lookup order:
 *   1. In-memory session cache (Map)  — instant
 *   2. localStorage cache (~500 entries LRU) — persists session
 *   3. /api/roots-analyze (Vercel edge) — Dicta Nakdan + DictaBERT-lex fallback (Hebrew only)
 *   4. Null (graceful degradation)
 *
 * rootMode drives the visual layer:
 *   'off'   — plain text, no annotation
 *   'roots' — root consonants highlighted (deep blue), affixes hollowed
 */

import { ref, computed, watch } from 'vue'

// ── Mode ──────────────────────────────────────────────────────────────────────

function loadMode() {
  const s = localStorage.getItem('szol_roots')
  if (s === '1' || s === 'manuscript') return 'roots'  // migrate old values
  if (['off', 'roots'].includes(s)) return s
  return 'off'
}

export const rootMode = ref(loadMode())

// Backward-compat alias (VocabView still uses this)
export const rootHighlightOn = computed(() => rootMode.value !== 'off')

watch(rootMode, v => localStorage.setItem('szol_roots', v))

// ── Cache ─────────────────────────────────────────────────────────────────────

const CACHE_KEY   = 'szol_root_cache_v3'  // v3: correct loadbalancer URL + new response format
const CACHE_LIMIT = 500
const _session    = new Map()   // `${lang}:${word}` → char[] | null

function _loadLocal() {
  try { return JSON.parse(localStorage.getItem(CACHE_KEY) || '{}') } catch { return {} }
}
function _saveLocal(store) {
  try { localStorage.setItem(CACHE_KEY, JSON.stringify(store)) } catch {}
}

function cacheGet(word, lang) {
  const key = `${lang}:${word}`
  if (_session.has(key)) return _session.get(key)
  const store = _loadLocal()
  if (key in store) { _session.set(key, store[key]); return store[key] }
  return undefined
}

function cacheSet(word, lang, root) {
  const key = `${lang}:${word}`
  _session.set(key, root)
  const store = _loadLocal()
  const keys  = Object.keys(store)
  if (keys.length >= CACHE_LIMIT) delete store[keys[0]]
  store[key] = root
  _saveLocal(store)
}

// ── API lookup ────────────────────────────────────────────────────────────────

const _inflight = new Map()

async function fetchRoot(word, lang) {
  const key = `${lang}:${word}`
  if (_inflight.has(key)) return _inflight.get(key)

  const promise = fetch('/api/roots-analyze', {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body:    JSON.stringify({ word, lang }),
  })
    .then(r => r.ok ? r.json() : null)
    .then(data => {
      const root = data?.root ?? null   // e.g. ["כ","ת","ב"] or null
      cacheSet(word, lang, root)
      _inflight.delete(key)
      return root
    })
    .catch(() => { _inflight.delete(key); return null })

  _inflight.set(key, promise)
  return promise
}

// ── Local root dictionaries (public/he-roots.json, public/ar-roots.json) ─────
// Generated by scripts/build-roots.py from Wiktionary dumps. Loaded once lazily.

const _localRoots = { he: null, ar: null }  // Map<word, char[]> once loaded

async function loadLocalRoots(lang) {
  if (_localRoots[lang]) return _localRoots[lang]
  try {
    const res = await fetch(`/${lang}-roots.json`)
    if (!res.ok) { _localRoots[lang] = new Map(); return _localRoots[lang] }
    const obj = await res.json()
    const m = new Map()
    for (const [k, v] of Object.entries(obj)) {
      let key = stripDiacritics(k)
      if (lang === 'ar') key = normalizeAlef(key)
      if (!m.has(key)) m.set(key, v)
    }
    _localRoots[lang] = m
    console.log(`[roots] ${lang} dict loaded: ${_localRoots[lang].size} entries`)
  } catch (e) {
    console.warn(`[roots] ${lang} dict load failed:`, e.message)
    _localRoots[lang] = new Map()
  }
  return _localRoots[lang]
}

// Strip diacritics so words match dictionary headwords.
function stripDiacritics(w) {
  return w.replace(/[ְ-ׇً-ٰٟـ]/g, '')
}

// Arabic alef variants all represent the same consonant in root patterns.
function normalizeAlef(w) {
  return w.replace(/[أإآٱ]/g, 'ا').replace(/ى/g, 'ي')
}

const PREFIXES = {
  // Ordered longest-first so greedier matches win.
  // Compound wa+prep prefixes (وبال، وللـ etc.) let two-clitic words be resolved in one pass.
  ar: ['وبال','وفال','وكال','ولل','وال','بال','كال','فال','لل','ال','وب','ول','وف','وك','و','ب','ل','ف','ك'],
  he: ['וה', 'וב', 'ול', 'וכ', 'ומ', 'וש', 'ה', 'ו', 'ב', 'ל', 'כ', 'מ', 'ש'],
}

const AR_SUFFIXES = [
  // Verb + pronoun clusters (longest first to avoid partial matches)
  'وهم','وها','يهم','تهم','يها','تها','تكم','تكن',
  'ية','هما','كما',
  'هم','هن','كم','كن','نا','تك','ته',
  'ون','ين','ات','ان','وا',
  'ها','ني','يا',
  'ي','ة',
]

function dictLookup(word, lang, dict) {
  const raw  = stripDiacritics(word)
  const norm = lang === 'ar' ? normalizeAlef(raw) : raw
  const candidates = (lang === 'ar' && norm !== raw) ? [raw, norm] : [raw]
  for (const w of candidates) {
    if (dict.has(w)) return dict.get(w)
    const pres = PREFIXES[lang] ?? []
    const sufs = lang === 'ar' ? AR_SUFFIXES : []
    for (const pre of pres) {
      if (w.startsWith(pre) && w.length > pre.length + 2) {
        const stem = w.slice(pre.length)
        if (dict.has(stem)) return dict.get(stem)
        for (const suf of sufs) {
          if (stem.endsWith(suf) && stem.length > suf.length + 2) {
            const core = stem.slice(0, stem.length - suf.length)
            if (dict.has(core)) return dict.get(core)
          }
        }
      }
    }
    for (const suf of sufs) {
      if (w.endsWith(suf) && w.length > suf.length + 2) {
        const stem = w.slice(0, w.length - suf.length)
        if (dict.has(stem)) return dict.get(stem)
      }
    }
  }
  return null
}
// ── Roots API via Vercel proxy ────────────────────────────────────────────────
// Hebrew: Dicta Nakdan + DictaBERT-lex HuggingFace fallback, via /api/roots-analyze.
// Arabic: local dict only (no REST API exposes triliteral roots keylessly).

async function rootsBatch(words, lang) {
  try {
    const res = await fetch('/api/roots-analyze', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ words, lang }),
    })
    const data = res.ok ? await res.json() : {}
    return data.roots ?? {}
  } catch {
    return {}
  }
}

async function dictaHebrewBatch(words) {
  try {
    const res = await fetch('/api/roots-analyze', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ words, lang: 'he' }),
    })
    const data = res.ok ? await res.json() : {}
    return data.roots ?? {}
  } catch {
    return {}
  }
}

// ── Public: batch pre-fetch for a word list ───────────────────────────────────
// Returns { word → rootString } for all words that have a known root.

export async function preFetchRoots(words, lang) {
  if (!['ar', 'he'].includes(lang)) return {}

  const unique   = [...new Set(words.filter(Boolean))]
  const map      = {}
  const uncached = []

  for (const word of unique) {
    const cached = cacheGet(word, lang)
    if (cached !== undefined) {
      if (Array.isArray(cached) && cached.length) map[word] = cached.join('')
    } else {
      uncached.push(word)
    }
  }

  if (!uncached.length) return map

  // 1. Check local dictionary — with diacritic stripping and prefix-stripped fallback
  const localDict = await loadLocalRoots(lang)
  const stillUncached = []
  for (const word of uncached) {
    const chars = dictLookup(word, lang, localDict)
    if (chars) {
      cacheSet(word, lang, chars)
      map[word] = chars.join('')
    } else {
      stillUncached.push(word)
    }
  }

  console.log(`[roots] ${lang} local hit: ${uncached.length - stillUncached.length}/${uncached.length} | miss: ${stillUncached.length}`)

  // 2. API for words not in local dict
  if (stillUncached.length) {
    try {
      const batchFn = lang === 'he' ? dictaHebrewBatch : rootsBatch
      const roots   = await batchFn(stillUncached, lang)
      for (const word of stillUncached) {
        const chars = roots[word] ?? null
        cacheSet(word, lang, chars)
        if (chars) map[word] = chars.join('')
      }
    } catch (e) {
      console.error('[roots] batch error:', e.message)
    }
  }

  return map
}

// ── CSS Custom Highlight API (root consonant highlighting) ────────────────────
// Used in VocabView for consonant-level marking within words.

const WORD_RE_HE    = /[א-תװ-ײ]+/g
const WORD_RE_AR    = /[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]+/g
const HE_VOWEL      = /[ְ-ׇ]/
const AR_VOWEL      = /[ً-ٰٟ]/

export function clearRoots() {
  CSS.highlights?.delete('szol-root')
  CSS.highlights?.delete('szol-affix')
}

function stripVowels(text, lang) {
  return lang === 'he' ? text.replace(/[ְ-ׇ]/g, '')
       : lang === 'ar' ? text.replace(/[ً-ٰٟ]/g, '')
       : text
}

function buildIndexMap(word, lang) {
  const isVowel = lang === 'he' ? c => HE_VOWEL.test(c) : c => AR_VOWEL.test(c)
  const map = []
  for (let i = 0; i < word.length; i++) {
    if (!isVowel(word[i])) map.push(i)
  }
  return map
}

function findRootRanges(word, rootChars, lang) {
  const stripped = stripVowels(word, lang)
  const idxMap   = buildIndexMap(word, lang)
  const ranges   = []
  let ri = 0
  for (let si = 0; si < stripped.length && ri < rootChars.length; si++) {
    if (stripped[si] === rootChars[ri]) {
      const origStart = idxMap[si]
      let origEnd = origStart + 1
      while (origEnd < word.length && (HE_VOWEL.test(word[origEnd]) || AR_VOWEL.test(word[origEnd]))) origEnd++
      ranges.push({ start: origStart, end: origEnd })
      ri++
    }
  }
  return ri === rootChars.length ? ranges : null
}

// Build affix ranges: letter+mark positions in the word not covered by root ranges.
function buildAffixRanges(word, rootRanges) {
  const covered = new Set()
  for (const { start, end } of rootRanges)
    for (let i = start; i < end; i++) covered.add(i)
  const result = []
  let start = null
  for (let i = 0; i <= word.length; i++) {
    const isAffix = i < word.length && /[\p{L}\p{M}]/u.test(word[i]) && !covered.has(i)
    if (isAffix && start === null) start = i
    else if (!isAffix && start !== null) { result.push({ start, end: i }); start = null }
  }
  return result
}

export async function applyRoots(containerEl, lang) {
  if (!rootHighlightOn.value) return
  if (!CSS.highlights) return
  if (!containerEl) return
  if (lang !== 'he' && lang !== 'ar') return

  const wordRe   = lang === 'he' ? WORD_RE_HE : WORD_RE_AR
  const rootList  = []
  const affixList = []

  function addWordRanges(node, word, offset, rootChars) {
    const rr = findRootRanges(word, rootChars, lang)
    if (!rr) return
    for (const { start, end } of rr) {
      const r = new Range(); r.setStart(node, offset + start); r.setEnd(node, offset + end)
      rootList.push(r)
    }
    for (const { start, end } of buildAffixRanges(word, rr)) {
      const r = new Range(); r.setStart(node, offset + start); r.setEnd(node, offset + end)
      affixList.push(r)
    }
  }

  function commit() {
    CSS.highlights.set('szol-root',  new Highlight(...rootList))
    CSS.highlights.set('szol-affix', new Highlight(...affixList))
  }

  const walker  = document.createTreeWalker(containerEl, NodeFilter.SHOW_TEXT)
  const pending = []
  let node
  while ((node = walker.nextNode())) {
    const text = node.textContent
    wordRe.lastIndex = 0
    let m
    while ((m = wordRe.exec(text)) !== null) {
      const cached = cacheGet(m[0], lang)
      if (cached !== undefined) {
        if (cached) addWordRanges(node, m[0], m.index, cached)
      } else {
        pending.push({ node, word: m[0], wordOffset: m.index })
      }
    }
  }

  commit()

  if (pending.length) {
    const unique = [...new Set(pending.map(p => p.word))]
    await Promise.all(unique.map(w => fetchRoot(w, lang)))
    for (const { node, word, wordOffset } of pending) {
      const root = cacheGet(word, lang)
      if (root) addWordRanges(node, word, wordOffset, root)
    }
    commit()
  }
}