// transcriptCache.js — IndexedDB storage for user-imported YouTube transcripts.
// Transcripts are keyed by `${videoId}:${lang}` and stored locally forever
// (until the user clears browser data). No server storage involved.

const DB_NAME    = 'szol-transcripts'
const STORE_NAME = 'imports'
const DB_VERSION = 1

function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION)
    req.onupgradeneeded = e => {
      const db = e.target.result
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'key' })
      }
    }
    req.onsuccess = e => resolve(e.target.result)
    req.onerror   = e => reject(e.target.error)
  })
}

function storeKey(videoId, lang) {
  return `${videoId}:${lang}`
}

// Save a transcript result. `data` should be { video_id, title, lang, is_autogenerated, segments }.
export async function cacheImport(data) {
  const db  = await openDB()
  const row = { key: storeKey(data.video_id, data.lang), ...data, savedAt: Date.now() }
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite')
    tx.objectStore(STORE_NAME).put(row)
    tx.oncomplete = () => resolve()
    tx.onerror    = e => reject(e.target.error)
  })
}

// Retrieve a cached transcript, or null if not found.
export async function getCachedImport(videoId, lang) {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly')
    const req = tx.objectStore(STORE_NAME).get(storeKey(videoId, lang))
    req.onsuccess = e => resolve(e.target.result ?? null)
    req.onerror   = e => reject(e.target.error)
  })
}

// Return all cached imports sorted newest-first.
export async function listCachedImports() {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly')
    const req = tx.objectStore(STORE_NAME).getAll()
    req.onsuccess = e => resolve(
      (e.target.result ?? []).sort((a, b) => (b.savedAt ?? 0) - (a.savedAt ?? 0))
    )
    req.onerror = e => reject(e.target.error)
  })
}

// Remove a cached import.
export async function deleteCachedImport(videoId, lang) {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite')
    tx.objectStore(STORE_NAME).delete(storeKey(videoId, lang))
    tx.oncomplete = () => resolve()
    tx.onerror    = e => reject(e.target.error)
  })
}

// Search all cached videos for a specific word.
// Returns [{video_id, title, hits: [{start, raw, context}]}] sorted by hit count.
// Only videos imported after word-level data was added will have words to search.
export async function searchWordInImports(word, lang) {
  const all    = await listCachedImports().catch(() => [])
  const target = word.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '')
  if (!target) return []

  const results = []
  for (const imp of all) {
    if (imp.lang !== lang || !imp.words?.length) continue
    const hits = imp.words.filter(w => w.word === target)
    if (!hits.length) continue
    results.push({
      video_id: imp.video_id,
      title:    imp.title,
      hits:     hits.slice(0, 6).map(h => ({
        start:   h.start,
        raw:     h.raw,
        context: _findContext(imp.segments, h.start),
      })),
    })
  }
  return results.sort((a, b) => b.hits.length - a.hits.length)
}

function _findContext(segments, startSec) {
  if (!segments?.length) return ''
  const seg = segments.find(s => s.start <= startSec && s.end >= startSec)
  if (seg) return seg.text
  return segments.filter(s => s.end <= startSec).pop()?.text ?? ''
}
