// transcriptCache.js — IndexedDB storage for user-imported YouTube transcripts.
// Transcripts are keyed by `${videoId}:${lang}` and stored locally forever
// (until the user clears browser data). No server storage involved.

const DB_NAME    = 'szol-transcripts'
const STORE_NAME = 'imports'
const DB_VERSION = 1

function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION)
    req.onupgradeneeded = e => {
      const db = e.target.result
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'key' })
      }
    }
    req.onsuccess = e => resolve(e.target.result)
    req.onerror   = e => reject(e.target.error)
  })
}

function storeKey(videoId, lang) {
  return `${videoId}:${lang}`
}

// Save a transcript result. `data` should be { video_id, title, lang, is_autogenerated, segments }.
export async function cacheImport(data) {
  const db  = await openDB()
  const row = { key: storeKey(data.video_id, data.lang), ...data, savedAt: Date.now() }
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite')
    tx.objectStore(STORE_NAME).put(row)
    tx.oncomplete = () => resolve()
    tx.onerror    = e => reject(e.target.error)
  })
}

// Retrieve a cached transcript, or null if not found.
export async function getCachedImport(videoId, lang) {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly')
    const req = tx.objectStore(STORE_NAME).get(storeKey(videoId, lang))
    req.onsuccess = e => resolve(e.target.result ?? null)
    req.onerror   = e => reject(e.target.error)
  })
}

// Return all cached imports sorted newest-first.
export async function listCachedImports() {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly')
    const req = tx.objectStore(STORE_NAME).getAll()
    req.onsuccess = e => resolve(
      (e.target.result ?? []).sort((a, b) => (b.savedAt ?? 0) - (a.savedAt ?? 0))
    )
    req.onerror = e => reject(e.target.error)
  })
}

// Remove a cached import.
export async function deleteCachedImport(videoId, lang) {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite')
    tx.objectStore(STORE_NAME).delete(storeKey(videoId, lang))
    tx.oncomplete = () => resolve()
    tx.onerror    = e => reject(e.target.error)
  })
}
